### ISSUE TITLE
about: Gabe missing from leadership team

### ISSUE THREAD

**Issue by gmugar** [engagementgamelab/boston-civic-media#104]
Gabe is missing from leadership team. 

you can find photo at bottom of this page: https://civicimagination.splashthat.com/

Title: Associate Researcher and Affiliate Faculty, Engagement Lab; Faculty Coordinator, Boston Civic Media

**Comment by jpailthorpe** [comment]
I edited Gabe's photo to better match. It is definitely not ideal (since the bio photo was taken with the shoulder cutout, so i couldn't center) and a photo should be taken to match the others eventually, but I think it is okay for now. I tested with Christina and she couldn't notice it was photoshopped until I pointed it out.
