### ISSUE TITLE
LightningTalks: update mockup to include sorting by event

### ISSUE THREAD

**Issue by kanarinka** [engagementgamelab/boston-civic-media#13]
Categories filter content that is not visible to user and thus are very confusing. Please remove the category buttons entirely. Labeling this as a bug because it is making content completely unusable.

Then, list all of the lightning talk videos by event. Make the event titles Header 2's and order the events in reverse chronological order, with the most recent event FIRST on the page.

**Comment by jpailthorpe** [comment]
might need a quick wire to show this visually...also a bit concerned this would make this entire page simply like the more detailed past event pages:

https://bostoncivic.media/events/civic-media-impact-and-assessmentlesspgreaterapril-2016lesspgreater

Wondering if there is an opportunity to combine these into one page with a sleek design that organizes this information better. Only suggesting because this would create a much better information hierarchy and be easier to maintain/update.

**Comment by jpailthorpe** [comment]
another way to approach this without messing with events but keeping the same backend tech, is to simply change the way the category system is displayed alongside the videos. For example, not showing the featured lightning talk video alongside the categories, but instead above them. then when user scrolls down, they see either an anchored list on the left with the categories (like the courses page) OR they are displayed horizontally, and small enough across so that the lightning talk video blocks can be seen shifting.

**Comment by jpailthorpe** [comment]
This has been updated to the new event page. the filter does not allow for filtering by event, and there is another issue that needs to be addressed for mobile ( #92 ) but other than that the majority of problems in this issue have been fixed.
