### ISSUE TITLE
AboutPage: Link text in about page to on home to Community action research project page on elab site. 

### ISSUE THREAD

**Issue by codeworthy** [engagementgamelab/boston-civic-media#15]
Multiple times we have tried to fix the About page which is supposed to link to the CIRB page in this sentence: "To learn more, read about some of the local to have formed from the network, notably an effort to create for collaborative, participatory research in Boston." with this link: https://elab.emerson.edu/projects/participation-and-engagement/a-community-approach-to-research-partnerships-carp

**Comment by jpailthorpe** [comment]
Possible reason is the text was not wrapped correctly in HREF tags (noted below). 

Although a possible bigger issue is that these two links are located no where else in the main navigation, combined with being somewhat hidden inside a paragraph, makes it almost impossible to find unless you accidentally stumble upon it. So unless this is somewhat intentional, I suggest thinking about a lite IA ordering, or moving this work into a "projects" block on the main page. 

<img width="1439" alt="screen shot 2017-05-08 at 7 04 13 pm" src="https://cloud.githubusercontent.com/assets/10051544/25829082/210cbfec-3422-11e7-9e09-722063aceb18.png">
<img width="1461" alt="screen shot 2017-05-08 at 7 09 11 pm" src="https://cloud.githubusercontent.com/assets/10051544/25829083/2114d146-3422-11e7-8e0a-857278e5f1b1.png">

**Comment by jpailthorpe** [comment]
larger org question: is this more of a elab project out of bcm? because all of the updated copy including the MOU template is hosted on our site. However, it is called Community Approach to research Partnerships, and the copy is differently framed on theelab site versus the copy that is currently on the production version of the bcm site. We have a mockup for this page (as before it wasn't contextualized) but still feel it is quite out of place in terms of site infrastructure. 

elab site:
https://elab.emerson.edu/projects/participation-and-engagement/a-community-approach-to-research-partnerships-carp

BCM site:
https://bostoncivic.media/irb_proj

I am going to completely hold on this until there is more clarity, but it is worth understand how this is dovetailing into the two brands (since hosting double content is dangerous in terms of updating/keeping current) and making sure this isn't confusingly placed on the site with no concrete understanding of where you can access the page (outside of the headerblocks).

**Comment by jpailthorpe** [comment]
https://zpl.io/y3EEq Zeplin mockup

**Comment by kanarinka** [comment]
I think it is fine to link the text referencing the Community IRB to the page on the elab website about it. Let's do that for now.

**Comment by jpailthorpe** [comment]
@johnnycrich feel free for me to update this about page copy mock to include this sentence as link.

**Comment by jpailthorpe** [comment]
I edited this copy to remove the link to the old collaborations page and reworded slightly to make sense. I also linked to the elab project page carp per catherine's suggestion. feel free to edit language further if youd like in keystone @codeworthy
