### ISSUE TITLE
About Page: Funder logos formatting

### ISSUE THREAD

**Issue by kanarinka** [engagementgamelab/boston-civic-media#83]
Microsoft logo is stretched and weird. Also, please center align the logos for that section since there are only two of them there.

**Comment by jpailthorpe** [comment]
I updated the microsoft logo to better match. @johnnycrich will just need to center align section

Agree this whole section needs work. This is something i noticed during this process, but since it was always this way even in the original site, I didn't want to dive into this change (since we basically would need to obtain all of these logos in svg and/or resize them to work correctly with our formatting, which would take a lot of work from just the content gathering side of things).
